"use client";
import { useEffect, useState } from 'react';
import { Edit3, Heart, Shirt, Trash2 } from 'lucide-react';
import PageHeader from '@/components/layout/PageHeader';
import Modal from '@/components/ui/Modal';
import ConfirmModal from '@/components/ui/ConfirmModal';
import OutfitEditor, { OutfitEditorItem, OutfitEditorValue } from '@/components/outfits/OutfitEditor';

type Outfit = OutfitEditorValue & { id: string };

export default function FavoritesClient(){const [data,setData]=useState<any>({items:[],outfits:[]});const [editing,setEditing]=useState<Outfit|null>(null);const [deleting,setDeleting]=useState<Outfit|null>(null);const [items,setItems]=useState<OutfitEditorItem[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
async function load(){const [favoriteResponse,clothingResponse]=await Promise.all([fetch('/api/favorites',{cache:'no-store'}),fetch('/api/clothing',{cache:'no-store'})]);const favorite=await favoriteResponse.json().catch(()=>({}));const clothing=await clothingResponse.json().catch(()=>({}));setData({items:favorite.items||[],outfits:favorite.outfits||[]});setItems(clothing.items||[]);}useEffect(()=>{void load()},[]);
async function toggle(item:any){const r=await fetch(`/api/clothing/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_favorite:false})});if(r.ok)await load();}
async function edit(value:any){if(!editing)return;setBusy(true);const r=await fetch(`/api/outfits/${editing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const j=await r.json().catch(()=>({}));if(r.ok){setEditing(null);await load()}else setMessage(j.error||'Não foi possível atualizar o look.');setBusy(false)}
async function remove(){if(!deleting)return;setBusy(true);const r=await fetch(`/api/outfits/${deleting.id}`,{method:'DELETE'});if(r.ok){setDeleting(null);await load()}else{const j=await r.json().catch(()=>({}));setMessage(j.error||'Não foi possível excluir o look.')}setBusy(false)}
return <><PageHeader/><h1 className="page-title">Favoritos</h1><p className="page-subtitle">Peças e looks que você quis guardar com carinho.</p>{message&&<div className="card inline-message" role="alert">{message}</div>}<section className="section"><div className="section-head"><h2 className="section-title">Peças favoritas</h2></div>{data.items.length?<div className="grid">{data.items.map((item:any)=><article key={item.id} className="card clothing-card"><button className="favorite-btn" aria-label="Desfavoritar" onClick={()=>void toggle(item)}><Heart size={17} fill="currentColor"/></button><div className="clothing-image">{item.image_path?<img src={`/api/media?path=${encodeURIComponent(item.image_path)}`} alt={item.name}/>:<div className="placeholder-art"><Shirt/></div>}</div><div className="clothing-info"><div className="clothing-name">{item.name}</div><div className="clothing-meta">{item.clothing_categories?.name||'Sem categoria'}</div></div></article>)}</div>:<div className="empty">Nenhuma peça favorita ainda.</div>}</section><section className="section"><div className="section-head"><h2 className="section-title">Looks favoritos</h2></div>{data.outfits.length?<div className="grid">{data.outfits.map((outfit:Outfit)=><article className="card outfit-card" key={outfit.id}><div className="outfit-preview">{(outfit.outfit_items||[]).slice(0,3).map((entry:any)=><img key={entry.clothing_item_id} src={entry.clothing_items?.image_path?`/api/media?path=${encodeURIComponent(entry.clothing_items.image_path)}`:undefined} alt=""/>)}{!(outfit.outfit_items||[]).length&&<div className="outfit-placeholder"><Shirt/></div>}</div><div className="outfit-info"><div className="outfit-title">{outfit.name}</div><div className="outfit-meta">{outfit.occasion||'Look salvo'}</div><div className="inline-actions" style={{marginTop:10}}><button className="btn btn-soft" onClick={()=>setEditing(outfit)}><Edit3 size={15}/>Editar</button><button className="btn btn-danger" onClick={()=>setDeleting(outfit)}><Trash2 size={15}/>Excluir</button></div></div></article>)}</div>:<div className="empty">Nenhum look favorito ainda.</div>}</section>{editing&&<Modal title="Editar look favorito" onClose={()=>setEditing(null)} wide><OutfitEditor initial={editing} items={items} onSave={edit} onCancel={()=>setEditing(null)} saving={busy}/></Modal>}{deleting&&<ConfirmModal title="Excluir look?" message="A composição será removida e esta ação não poderá ser desfeita." confirmLabel="Excluir look" onConfirm={()=>void remove()} onCancel={()=>setDeleting(null)} busy={busy}/>}</>}
