"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Heart, Moon, Shirt, Sparkles } from 'lucide-react';
import PageHeader from '@/components/layout/PageHeader';
import type { Outfit } from '@/lib/types';

export default function HomeClient(){ const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/home').then(r=>r.json()).then(setData).finally(()=>setLoading(false));},[]);
 if(loading)return <><PageHeader/><div className="flower-row"><i className="flower a"/><i className="flower b"/><i className="flower c"/></div><div className="empty">Carregando seu guarda-roupa…</div></>;
 const name=data?.profile?.name?.split(' ')[0]||'você'; const outfits=(data?.outfits||[]) as Outfit[]; return <><PageHeader/><div className="flower-row"><i className="flower a"/><i className="flower b"/><i className="flower c"/><i className="flower d"/></div><header><h1 className="page-title">Meu Look ♡</h1><p className="page-subtitle">Hoje é um bom dia para se sentir linda, {name}.</p></header>{data?.message&&<section className="section"><div className="card message-card"><Sparkles className="message-mark" size={19}/><div><p className="message-title">{data.message.title}</p><p className="message-body">{data.message.body}</p></div></div></section>}<section className="section"><div className="home-grid"><Link className="card hero-card" href="/look-do-dia"><span className="hero-icon"><Shirt size={22}/></span><div><span className="card-kicker">Hoje</span><h2 className="card-title">Look do Dia</h2><p className="card-copy">Escolha seu look perfeito para hoje.</p></div></Link><Link className="card hero-card" href="/guarda-roupa?category=Pijamas"><span className="hero-icon"><Moon size={22}/></span><div><span className="card-kicker">Conforto</span><h2 className="card-title">Pijamas</h2><p className="card-copy">Conforto e estilo até na hora de dormir.</p></div></Link></div></section><section className="section"><div className="section-head"><h2 className="section-title">Sugestões para você</h2></div>{outfits.length?<div className="grid">{outfits.slice(0,4).map((o:any)=><OutfitCard key={o.id} outfit={o}/>)}</div>:<div className="empty"><Sparkles className="empty-icon"/><h3 className="empty-title">Ainda não há looks aqui.</h3><p className="empty-copy">Salve alguns looks no seu guarda-roupa e eles aparecem nesta área.</p><Link className="btn btn-soft" href="/look-do-dia">Montar um look</Link></div>}</section><section className="section"><div className="section-head"><h2 className="section-title">Seus looks salvos</h2><Link className="text-link" href="/favoritos">Ver favoritos</Link></div>{(data?.saved||[]).length?<div className="grid">{data.saved.slice(0,4).map((o:any)=><OutfitCard key={o.id} outfit={o}/>)}</div>:<p className="page-subtitle">Você ainda não favoritou nenhum look.</p>}</section></> }
function OutfitCard({outfit}:any){const items=outfit.outfit_items||[];return <article className="card outfit-card"><div className="outfit-preview">{items.slice(0,3).map((it:any)=><img key={it.clothing_item_id} src={it.clothing_items?.image_path?`/api/media?path=${encodeURIComponent(it.clothing_items.image_path)}`:undefined} alt=""/>)}{items.length===0&&<div className="outfit-placeholder"><Shirt/></div>}</div><div className="outfit-info"><div className="outfit-title">{outfit.name}</div><div className="outfit-meta">{outfit.occasion||'Look salvo'}</div></div></article>}
