"use client";

import { Activity, ArrowRight, Heart, Shirt } from 'lucide-react';

const clothes = ['Vestido floral', 'Blusa rosé', 'Saia preta', 'Jaqueta jeans', 'Calça clara', 'Bolsa vinho'];

function Fabric({ index }: { index: number }) { return <div className={`debug-fabric debug-fabric-${index % 6}`}/>; }

export default function AdminPreviewView({ page }: { page: string }) {
  const titleMap: Record<string, string> = {
    '/inicio': 'Início', '/guarda-roupa': 'Guarda-Roupa', '/favoritos': 'Favoritos', '/calendario': 'Calendário',
    '/estatisticas': 'Estatísticas', '/configuracoes': 'Configurações', '/look-do-dia': 'Look do Dia'
  };
  const title = titleMap[page] || 'Meu Look';
  return <main className="debug-preview-app"><header className="topbar"><div className="mobile-brand"><img src="/pink-lily.svg" alt="" className="mobile-brand-lily"/><span>Meu Look</span></div><button className="icon-btn" aria-label="Sair"><Activity size={17}/></button></header><div className="content-area debug-preview-area"><span className="card-kicker">Meu Look</span><h1 className="page-title">{title}</h1><p className="page-subtitle">Prévia visual responsiva para o painel de debug.</p>{page === '/inicio' && <HomePreview/>}{page === '/guarda-roupa' && <WardrobePreview/>}{page === '/favoritos' && <FavoritesPreview/>}{page === '/calendario' && <CalendarPreview/>}{page === '/estatisticas' && <StatsPreview/>}{page === '/configuracoes' && <SettingsPreview/>}{page === '/look-do-dia' && <LookPreview/>}</div><nav className="mobile-nav" aria-label="Prévia de navegação"><a className="mobile-link active" href="#"><Activity size={18}/><span>Início</span></a><a className="mobile-link" href="#"><Shirt size={18}/><span>Roupa</span></a><a className="mobile-link" href="#"><Heart size={18}/><span>Favoritos</span></a><a className="mobile-link" href="#"><Activity size={18}/><span>Calendário</span></a><button type="button" className="mobile-link"><span>Mais</span></button></nav></main>;
}

function HomePreview() { return <><section className="section home-main-section"><div className="card home-day-look"><div className="section-head"><div><span className="card-kicker">Hoje</span><h2 className="card-title">Look do Dia</h2><p className="page-subtitle">Uma composição para começar o dia.</p></div><button className="text-link">Visualizar</button></div><div className="outfit-preview home-day-preview">{clothes.slice(0,4).map((name,i)=><div className="debug-preview-piece" key={name}><Fabric index={i}/><span>{name}</span></div>)}</div></div><div className="home-quick-actions"><button className="quick-action"><span><Shirt size={18}/></span><div><strong>Adicionar peça</strong><small>Atualize seu guarda-roupa</small></div><ArrowRight size={16}/></button><button className="quick-action"><span><Activity size={18}/></span><div><strong>Montar look</strong><small>Crie uma nova composição</small></div><ArrowRight size={16}/></button></div></section><section className="section home-summary-row"><div><strong>47</strong><span>peças</span></div><div><strong>18</strong><span>looks</span></div><div><strong>12</strong><span>favoritas</span></div><div><strong>9</strong><span>esperando sua vez</span></div></section></>; }
function WardrobePreview(){return <><div className="category-filter-row"><button className="btn btn-soft">Todas</button><button className="btn btn-ghost">Vestidos</button><button className="btn btn-ghost">Blusas</button><button className="btn btn-ghost">Calças</button></div><div className="grid debug-preview-grid">{clothes.map((name,i)=><article className="card clothing-card" key={name}><div className="clothing-image"><Fabric index={i}/></div><div className="clothing-info"><strong>{name}</strong><span>Categoria</span></div></article>)}</div></>}
function FavoritesPreview(){return <><div className="debug-preview-tabline"><span className="active">Peças favoritas</span><span>Looks favoritos</span></div><div className="grid debug-preview-grid">{clothes.slice(0,4).map((name,i)=><article className="card clothing-card" key={name}><div className="clothing-image"><Fabric index={i}/><button className="favorite-btn" aria-label={`Remover ${name} dos favoritos`}>♥</button></div><div className="clothing-info"><strong>{name}</strong><span>Favorita</span></div></article>)}</div></>}
function CalendarPreview(){return <div className="card debug-calendar-preview"><div className="section-head"><div><span className="card-kicker">Setembro 2026</span><h2 className="card-title">Calendário</h2></div><div className="inline-actions"><button className="icon-btn" aria-label="Mês anterior">‹</button><button className="icon-btn" aria-label="Próximo mês">›</button></div></div><div className="calendar-weekdays">{['D','S','T','Q','Q','S','S'].map((day,i)=><span key={`${day}-${i}`}>{day}</span>)}</div><div className="calendar-grid">{Array.from({length:35},(_,i)=><div className={`calendar-cell ${[5,11,18,25].includes(i)?'has-entry':''}`} key={i}><span>{i+1}</span>{[5,11,18,25].includes(i)&&<small>Look</small>}</div>)}</div></div>}
function StatsPreview(){return <><section className="stats-cards"><div className="card stat-card"><div className="stat-label">Peças</div><div className="stat-value">47</div></div><div className="card stat-card"><div className="stat-label">Looks</div><div className="stat-value">18</div></div><div className="card stat-card"><div className="stat-label">Favoritas</div><div className="stat-value">12</div></div><div className="card stat-card"><div className="stat-label">Dias registrados</div><div className="stat-value">16</div></div></section><section className="section stats-grid"><div className="card stats-panel"><div className="section-head"><div><h2 className="section-title">Mais usadas</h2></div></div>{clothes.slice(0,4).map((name,i)=><div className="usage-row" key={name}><div className="home-piece-thumb"><Fabric index={i}/></div><div><strong>{name}</strong><span>{i+1} usos</span></div></div>)}</div><div className="card stats-panel"><div className="section-head"><div><h2 className="section-title">Peças pouco usadas</h2></div></div>{clothes.slice(3).map((name,i)=><div className="usage-row" key={name}><div><strong>{name}</strong><span>{i%2===0?'1 uso':'2 usos'}</span></div></div>)}</div></section></>}
function SettingsPreview(){return <section className="section"><div className="card form-card"><h2 className="section-title">Sua conta</h2><div className="form-grid"><div className="field"><label className="label">Nome</label><div className="input">Lívia</div></div><div className="field"><label className="label">E-mail</label><div className="input">livia@example.com</div></div><div className="field full"><label className="label">Preferências</label><div className="check-row">Notificações suaves e lembretes</div></div></div></div></section>}
function LookPreview(){return <section className="section"><div className="card day-look-card"><div className="section-head"><div><span className="card-kicker">Escolhido</span><h2 className="card-title">Domingo tranquilo</h2><p className="page-subtitle">Passeio · confortável</p></div><button className="favorite-btn" aria-label="Favoritar look">♥</button></div><div className="outfit-preview day-look-preview">{clothes.slice(0,3).map((name,i)=><div className="debug-preview-piece" key={name}><Fabric index={i}/><span>{name}</span></div>)}</div></div></section>}
