"use client";
import { useEffect, useState } from 'react';
import { Check, Edit3, Plus, Power, Trash2 } from 'lucide-react';
import Modal from '@/components/ui/Modal';
import ConfirmModal from '@/components/ui/ConfirmModal';

type Category = { id:string; name:string; user_id:string|null; is_active:boolean; created_at:string };

export default function AdminCategoriesClient(){const [categories,setCategories]=useState<Category[]>([]);const [message,setMessage]=useState('');const [name,setName]=useState('');const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<Category|null>(null);const [deleting,setDeleting]=useState<Category|null>(null);const [busy,setBusy]=useState(false);
async function load(){const r=await fetch('/api/admin/categories',{cache:'no-store'});const j=await r.json().catch(()=>({}));setCategories(j.categories||[]);if(!r.ok)setMessage(j.error||'Selecione uma usuária.')}useEffect(()=>{void load()},[]);
async function create(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch('/api/admin/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const j=await r.json().catch(()=>({}));if(r.ok){setName('');setCreating(false);await load()}else setMessage(j.error||'Não foi possível criar a categoria.');setBusy(false)}
async function update(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);const r=await fetch('/api/admin/categories',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,name:editing.name,is_active:editing.is_active})});const j=await r.json().catch(()=>({}));if(r.ok){setEditing(null);await load()}else setMessage(j.error||'Não foi possível atualizar a categoria.');setBusy(false)}
async function toggle(category:Category){setBusy(true);const r=await fetch('/api/admin/categories',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:category.id,is_active:!category.is_active})});const j=await r.json().catch(()=>({}));if(r.ok)setCategories((current)=>current.map((item)=>item.id===category.id?{...item,is_active:!item.is_active}:item));else setMessage(j.error||'Não foi possível alterar a categoria.');setBusy(false)}
async function remove(){if(!deleting)return;setBusy(true);const r=await fetch('/api/admin/categories',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deleting.id})});const j=await r.json().catch(()=>({}));if(r.ok){setDeleting(null);await load()}else setMessage(j.error||'Não foi possível excluir a categoria.');setBusy(false)}
return <><h1 className="page-title">Categorias</h1><p className="page-subtitle">Gerencie as categorias específicas da usuária selecionada. As categorias padrão continuam disponíveis.</p>{message&&<div className="card inline-message" role="alert">{message}</div>}<div className="section-head section"><div><h2 className="section-title">Categorias</h2></div><button className="btn btn-primary" onClick={()=>setCreating(true)}><Plus size={17}/>Criar categoria</button></div><section className="section"><div className="category-admin-list">{categories.map((category)=><article className={`card category-admin-item${category.is_active?'':' inactive'}`} key={category.id}><div><div className="clothing-name">{category.name}</div><div className="clothing-meta">{category.user_id?'Personalizada':'Padrão'} · {category.is_active?'Ativa':'Desativada'}</div></div>{category.user_id&&<div className="inline-actions"><button className="btn btn-soft" onClick={()=>setEditing(category)}><Edit3 size={15}/>Editar</button><button className="btn btn-ghost" onClick={()=>void toggle(category)} disabled={busy}><Power size={15}/>{category.is_active?'Desativar':'Ativar'}</button><button className="btn btn-danger" onClick={()=>setDeleting(category)}><Trash2 size={15}/>Excluir</button></div>}</article>)}</div></section>{creating&&<Modal title="Nova categoria" onClose={()=>setCreating(false)}><form className="auth-form" onSubmit={create}><div className="field"><label className="label">Nome</label><input className="input" maxLength={40} value={name} onChange={(e)=>setName(e.target.value)} required/></div><div className="modal-actions inline-actions"><button type="button" className="btn btn-ghost" onClick={()=>setCreating(false)}>Cancelar</button><button className="btn btn-primary" disabled={busy}>{busy?'Salvando…':'Criar categoria'}</button></div></form></Modal>}{editing&&<Modal title="Editar categoria" onClose={()=>setEditing(null)}><form className="auth-form" onSubmit={update}><div className="field"><label className="label">Nome</label><input className="input" maxLength={40} value={editing.name} onChange={(e)=>setEditing({...editing,name:e.target.value})} required/></div><label className="check-row"><input type="checkbox" checked={editing.is_active} onChange={(e)=>setEditing({...editing,is_active:e.target.checked})}/><Check size={17}/> Categoria ativa</label><div className="modal-actions inline-actions"><button type="button" className="btn btn-ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn btn-primary" disabled={busy}>Salvar alterações</button></div></form></Modal>}{deleting&&<ConfirmModal title="Excluir categoria?" message="Categorias usadas por peças existentes não podem ser apagadas. Nesse caso, use a opção de desativar." confirmLabel="Excluir" onConfirm={()=>void remove()} onCancel={()=>setDeleting(null)} busy={busy}/>}</>}
